version: "3"
services:
  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hairdress
    networks:
      - code-network
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
      - ./docker/sql_table:/opt/sql

  php:
    image: webdevops/php-apache-dev:7.0
    restart: always
    environment:
      WEB_DOCUMENT_ROOT: "/app/public"
      WEB_DOCUMENT_INDEX: "index.php index.html"
    ports:
      - 80:80
    links:
      - mysqldb
    volumes:
      - ./:/app
      - ./docker/php.ini:/opt/docker/etc/php/php.ini
    networks:
      - code-network
networks:
  code-network:
    driver: bridge