version: "3"
services:
  mysqldb:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - code-network
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/sql:/opt/sql
#    command: mysql -uroot -proot < /opt/sql/thinkcmf5_2018-02-10.sql

  php:
    image: webdevops/php-apache-dev:7.0
    restart: always
    environment:
      WEB_DOCUMENT_ROOT: "/app/public"
      WEB_DOCUMENT_INDEX: "index.php index.html"
    ports:
      - 80:80
    links:
      - mysqldb
    volumes:
      - ./:/app
      - ./docker/php.ini:/opt/docker/etc/php/php.ini
#      - ./docker1:/opt/docker
    networks:
      - code-network
networks:
  code-network:
    driver: bridge